language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
before_script: yarn run webpack
script:
  - yarn run $TEST_SUITE
after_success: yarn run coverage
env:
  - TEST_SUITE=test
  - TEST_SUITE=lint
